# Generated by Django 4.2.7 on 2025-07-17 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('task_assigned', '任务分配'), ('task_updated', '任务更新'), ('task_completed', '任务完成'), ('task_overdue', '任务逾期'), ('task_reviewed', '任务评价'), ('task_commented', '任务评论'), ('system_announcement', '系统公告'), ('user_mentioned', '用户提及')], max_length=30, verbose_name='通知类型')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读'), ('archived', '已归档')], default='unread', max_length=20, verbose_name='通知状态')),
                ('channels', models.JSONField(default=list, help_text='支持的渠道：system, email, sms, shihuatong', verbose_name='发送渠道')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='系统内通知')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='短信通知')),
                ('shihuatong_notifications', models.BooleanField(default=True, verbose_name='石化通通知')),
                ('task_assigned_notifications', models.BooleanField(default=True, verbose_name='任务分配通知')),
                ('task_updated_notifications', models.BooleanField(default=True, verbose_name='任务更新通知')),
                ('task_completed_notifications', models.BooleanField(default=True, verbose_name='任务完成通知')),
                ('task_overdue_notifications', models.BooleanField(default=True, verbose_name='任务逾期通知')),
                ('task_reviewed_notifications', models.BooleanField(default=True, verbose_name='任务评价通知')),
                ('task_commented_notifications', models.BooleanField(default=True, verbose_name='任务评论通知')),
                ('do_not_disturb_start', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('do_not_disturb_end', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户通知设置',
                'verbose_name_plural': '用户通知设置',
                'db_table': 'user_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('notification_type', models.CharField(choices=[('task_assigned', '任务分配'), ('task_updated', '任务更新'), ('task_completed', '任务完成'), ('task_overdue', '任务逾期'), ('task_reviewed', '任务评价'), ('task_commented', '任务评论'), ('system_announcement', '系统公告'), ('user_mentioned', '用户提及')], max_length=30, verbose_name='通知类型')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('content_template', models.TextField(verbose_name='内容模板')),
                ('default_channels', models.JSONField(default=list, verbose_name='默认发送渠道')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='模板状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'db_table': 'notification_templates',
                'unique_together': {('notification_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('system', '系统内通知'), ('email', '邮件'), ('sms', '短信'), ('shihuatong', '石化通')], max_length=20, verbose_name='发送渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('success', '发送成功'), ('failed', '发送失败'), ('retry', '重试中')], default='pending', max_length=20, verbose_name='发送状态')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='notifications.notification', verbose_name='通知')),
            ],
            options={
                'verbose_name': '通知发送日志',
                'verbose_name_plural': '通知发送日志',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
