# Generated by Django 4.2.7 on 2025-07-17 01:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('normal', '普通任务'), ('urgent', '紧急任务'), ('important', '重要任务'), ('routine', '例行任务')], default='normal', max_length=20, verbose_name='任务类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('assignment_mode', models.CharField(choices=[('one_to_one', '一对一分配'), ('one_to_many', '一对多分配'), ('cross_department', '跨部门协同')], default='one_to_one', max_length=20, verbose_name='分配模式')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('due_date', models.DateTimeField(verbose_name='截止时间')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='预估工时(小时)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待接收'), ('accepted', '已接收'), ('in_progress', '进行中'), ('completed', '已完成'), ('reviewed', '已评价'), ('cancelled', '已取消'), ('overdue', '已逾期')], default='draft', max_length=20, verbose_name='任务状态')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='是否有附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('creator_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='departments.department', verbose_name='创建部门')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='departments.profession', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', '牵头人'), ('collaborator', '协助者'), ('reviewer', '评审人')], default='collaborator', max_length=20, verbose_name='角色')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否为牵头人')),
                ('status', models.CharField(choices=[('pending', '待接收'), ('accepted', '已接收'), ('in_progress', '进行中'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='分配状态')),
                ('assignment_note', models.TextField(blank=True, verbose_name='分配备注')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('assignee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='departments.department', verbose_name='执行人部门')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务分配',
                'verbose_name_plural': '任务分配',
                'db_table': 'task_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('task', 'assignee')},
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(verbose_name='模板描述')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('description_template', models.TextField(verbose_name='描述模板')),
                ('task_type', models.CharField(choices=[('normal', '普通任务'), ('urgent', '紧急任务'), ('important', '重要任务'), ('routine', '例行任务')], default='normal', max_length=20, verbose_name='任务类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='预估工时(小时)')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='模板状态')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='departments.department', verbose_name='所属部门')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='departments.profession', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板',
                'db_table': 'task_templates',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '差'), (2, '一般'), (3, '良好'), (4, '优秀'), (5, '杰出')], verbose_name='评分')),
                ('quality_rating', models.PositiveIntegerField(choices=[(1, '差'), (2, '一般'), (3, '良好'), (4, '优秀'), (5, '杰出')], verbose_name='质量评分')),
                ('timeliness_rating', models.PositiveIntegerField(choices=[(1, '差'), (2, '一般'), (3, '良好'), (4, '优秀'), (5, '杰出')], verbose_name='及时性评分')),
                ('comments', models.TextField(verbose_name='评价意见')),
                ('suggestions', models.TextField(blank=True, verbose_name='改进建议')),
                ('is_satisfied', models.BooleanField(default=True, verbose_name='是否满意')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务评价',
                'verbose_name_plural': '任务评价',
                'db_table': 'task_reviews',
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('failed', '失败')], default='not_started', max_length=20, verbose_name='执行状态')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进度百分比')),
                ('result_description', models.TextField(blank=True, verbose_name='执行结果描述')),
                ('actual_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='实际工时(小时)')),
                ('issues_encountered', models.TextField(blank=True, verbose_name='遇到的问题')),
                ('risks_identified', models.TextField(blank=True, verbose_name='识别的风险')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='tasks.taskassignment', verbose_name='任务分配')),
            ],
            options={
                'verbose_name': '任务执行',
                'verbose_name_plural': '任务执行',
                'db_table': 'task_executions',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_type', models.CharField(choices=[('general', '一般评论'), ('question', '问题'), ('suggestion', '建议'), ('update', '进度更新')], default='general', max_length=20, verbose_name='评论类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment', verbose_name='父评论')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务评论',
                'verbose_name_plural': '任务评论',
                'db_table': 'task_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('attachment_type', models.CharField(choices=[('task_document', '任务文档'), ('reference', '参考资料'), ('result', '执行结果'), ('image', '图片'), ('other', '其他')], default='task_document', max_length=20, verbose_name='附件类型')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='任务')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'db_table': 'task_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='tasks_status_6c0c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creator', 'status'], name='tasks_creator_891a72_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creator_department', 'status'], name='tasks_creator_5e58e5_idx'),
        ),
    ]
