# Generated by Django 4.2.7 on 2025-07-17 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', '调试'), ('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=20, verbose_name='日志级别')),
                ('operation_type', models.CharField(choices=[('send_message', '发送消息'), ('user_sync', '用户同步'), ('config_update', '配置更新'), ('health_check', '健康检查')], max_length=30, verbose_name='操作类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '集成日志',
                'verbose_name_plural': '集成日志',
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShihuatongIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='集成名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('app_code', models.CharField(max_length=100, verbose_name='应用编码')),
                ('app_key', models.CharField(max_length=100, verbose_name='应用Key')),
                ('app_secret', models.CharField(max_length=200, verbose_name='应用Secret')),
                ('aes_key', models.CharField(max_length=100, verbose_name='AES密钥')),
                ('aes_iv', models.CharField(max_length=100, verbose_name='AES初始向量')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('error', '错误')], default='active', max_length=20, verbose_name='集成状态')),
                ('total_messages_sent', models.PositiveIntegerField(default=0, verbose_name='总发送消息数')),
                ('success_messages_sent', models.PositiveIntegerField(default=0, verbose_name='成功发送消息数')),
                ('failed_messages_sent', models.PositiveIntegerField(default=0, verbose_name='失败发送消息数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '石化通集成',
                'verbose_name_plural': '石化通集成',
                'db_table': 'shihuatong_integrations',
            },
        ),
        migrations.CreateModel(
            name='ShihuatongUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shihuatong_user_id', models.CharField(max_length=100, verbose_name='石化通用户ID')),
                ('shihuatong_username', models.CharField(max_length=100, verbose_name='石化通用户名')),
                ('shihuatong_display_name', models.CharField(max_length=100, verbose_name='石化通显示名称')),
                ('default_hook_token', models.CharField(blank=True, max_length=200, verbose_name='默认Hook Token')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用'), ('pending', '待验证')], default='pending', max_length=20, verbose_name='映射状态')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shihuatong_mapping', to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '石化通用户映射',
                'verbose_name_plural': '石化通用户映射',
                'db_table': 'shihuatong_user_mappings',
            },
        ),
        migrations.CreateModel(
            name='ShihuatongMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', '文本消息'), ('markdown', 'Markdown消息'), ('card', '卡片消息')], default='text', max_length=20, verbose_name='消息类型')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('hook_token', models.CharField(max_length=200, verbose_name='Hook Token')),
                ('recipient_user_ids', models.JSONField(blank=True, default=list, verbose_name='接收用户ID列表')),
                ('mention_all', models.BooleanField(default=False, verbose_name='是否@所有人')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('success', '发送成功'), ('failed', '发送失败'), ('retry', '重试中')], default='pending', max_length=20, verbose_name='发送状态')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.shihuatongintegration', verbose_name='集成配置')),
            ],
            options={
                'verbose_name': '石化通消息',
                'verbose_name_plural': '石化通消息',
                'db_table': 'shihuatong_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
