# Generated by Django 4.2.7 on 2025-07-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shihuatongmessage',
            name='related_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shihuatong_messages', to='notifications.notification', verbose_name='关联通知'),
        ),
    ]
