# Generated by Django 4.2.7 on 2025-07-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shihuatongmessage',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shihuatong_messages', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.shihuatongintegration', verbose_name='集成配置'),
        ),
        migrations.AlterUniqueTogether(
            name='shihuatongusermapping',
            unique_together={('shihuatong_user_id',)},
        ),
        migrations.AddIndex(
            model_name='shihuatongmessage',
            index=models.Index(fields=['status', 'created_at'], name='shihuatong__status_e96dac_idx'),
        ),
        migrations.AddIndex(
            model_name='shihuatongmessage',
            index=models.Index(fields=['related_task'], name='shihuatong__related_b36247_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['level', 'created_at'], name='integration_level_5e5cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['operation_type', 'created_at'], name='integration_operati_c71257_idx'),
        ),
    ]
