# Generated by Django 4.2.7 on 2025-07-17 01:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', '部门编码只能包含字母、数字、下划线和横线')], verbose_name='部门编码')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='层级')),
                ('type', models.CharField(choices=[('company', '公司'), ('division', '事业部'), ('department', '部门'), ('section', '科室'), ('team', '班组')], default='department', max_length=20, verbose_name='部门类型')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=20, verbose_name='部门状态')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='办公地址')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departments.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'departments',
                'ordering': ['level', 'sort_order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', '专业编码只能包含字母、数字、下划线和横线')], verbose_name='专业编码')),
                ('description', models.TextField(blank=True, verbose_name='专业描述')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=20, verbose_name='专业状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='departments.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'db_table': 'professions',
                'ordering': ['department', 'sort_order', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_type', models.CharField(choices=[('regular', '常规协作'), ('strategic', '战略协作'), ('project', '项目协作')], default='regular', max_length=20, verbose_name='协作类型')),
                ('description', models.TextField(blank=True, verbose_name='协作描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('primary_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_collaborations', to='departments.department', verbose_name='主导部门')),
                ('secondary_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_collaborations', to='departments.department', verbose_name='协作部门')),
            ],
            options={
                'verbose_name': '部门协作关系',
                'verbose_name_plural': '部门协作关系',
                'db_table': 'department_collaborations',
                'unique_together': {('primary_department', 'secondary_department')},
            },
        ),
    ]
